### ISSUE TITLE
Mistake in parsing income with commas

### ISSUE THREAD

**Issue by achalddave** [PurpleBracket/berniecare#7]
There seems to be a bug in parsing incomes with an incorrect number of commas, when commas should probably just be ignored. E.g. "1000,000" vs "1,000,000" gives different answers.

**Comment by wboykinm** [comment]
@achalddave Apologies, but I'm not able to enter commas at all - either typed or pasted. Can you share a screenshot, along with browser/OS?

**Comment by achalddave** [comment]
Browser: Firefox (44.0)
OS: Windows 10 (though I'm pretty sure this is applies to Firefox regardless of browser versions)

![berniecare-1](https://cloud.githubusercontent.com/assets/1168881/12697182/c9fb3b4c-c74a-11e5-8d87-6984b0ca2b30.PNG)
![berniecare-2](https://cloud.githubusercontent.com/assets/1168881/12697183/ca09f61e-c74a-11e5-9d01-6f08a965eadc.PNG)

**Comment by wboykinm** [comment]
Got it. Thanks. Looks windows-specific, so we're trying to add a handler for commas.
