### ISSUE TITLE
Users Being Misinformed By Your Calculator

### ISSUE THREAD

**Issue by sgoodrow** [PurpleBracket/berniecare#8]
Two users reported to me that your application assessed them as saving -$750/year due to Berniecare, here's why:

They are an employee of a state institution (University). They provided the following information:
Income: $96,000
People: 1
Annual Healthcare cost: $1000

The problem is in their understanding of their annual healthcare cost. $1000 is their annual healthcare cost. However their employer is contributing $6000 as well. Your calculator does not consider the employer savings, however even if it did, the user needs to understand that their employer may be obligated to increase their salary to maintain their total compensation. 

In this users case, they are able to opt-out of the employer's benefits (however they overlooked this), and the employer would be obligated to pay them 75% of the value of the benefits they were offering. This would equate to $4500/year, which would mean they would be saving $3750, not losing $750.

**Why does this need to be addressed?**
This is not a really special case. Many people work for large institutions that offer benefits, and a consequence of the ACA is that many of these employers must give them the right to opt-out and maintain their total compensation.

I can appreciate your trying to keep the applet simple, but it is misinforming people in a very counter-productive way. We need to explain this in the applet or users will walk away thinking Berniecare will cost them $1000/year instead of saving them $4000/year. We cannot overlook this.

**Comment by PurpleBracket** [comment]
@sgoodrow thank you so much for the detailed feedback, we're looking into the concerns you mentioned.
